project:
  type: default
  output-dir: _output
  render:
    - index.qmd
    - ppt.qmd

title: "Optimización de Portafolio Agrícola: Una Alternativa para la Mitigación de Riesgos en la República Dominicana"
date: last-modified
date-format: long

author:
  - name: Ian Contreras (1116048)
    emails:
      - personal: contreras.mejia@hotmail.com
      - institutional: 1116048@est.intec.edu.do
    phone: 809-856-0531
    affiliations:
      id: Intec
    attributes:
      corresponding: true
  
  - name: Elvis Lagrange (1109064)
    affiliations:
      id: Intec
    attributes:
      corresponding: true


affiliations:
  - id: Intec
    name: Instituto Tecnológico de Santo Domingo
    department: Economía y Negocios
    city: Santo Domingo
    country: República Dominicana


toc: true
bibliography: references.bib
citeproc: true
csl: https://www.zotero.org/styles/apa-with-abstract
lang: es

nocite: |
  @*

execute:
  freeze: true
  cache: true 
