---
title: Optimización Agricola
format: clean-typst
---

# Contenidos

## Contexto del sector

El sector agrícola representa una pieza clave para el desarrollo económico nacional.

-   Su valor agregado representa el 3% del Producto Interno Bruto.

-   Alrededor de 361,063 personas se encuentran trabajando en este sector o en sectores relacionados.

-   Las exportaciones agrícolas representan el $6.4\%$ de las exportaciones totales.

Sin embargo, existen ineficiencias estrucuturales y fallas del mercado que limitan su potencial de desarrollo.

## Desafíos del sector

El sector agrícola dominicano enfrenta serios desafíos que limitan su desarrollo y crecimiento:

-   **Alta concentración de la propiedad de la tierra**. El $77\%$ de los productores operan parcelas menores a 4.5 hectáreas, mientras que el 10% de los grandes productores: controlan el $61\%$ de la tierra agrícola.

    -   Esto genera una barrera para que los pequeños productores alcancen economías de escalas.

    -   Impide que los nuevos productores accendan a instrumentos sofisticados de gestión de riesgos.

-   **Infraetrcutura rural deplorable**. Sistemas de riego inadecuado, instalaciones de almacenamiento limitada, redes de trasnporte subdesarrolada, etc.

-   **Alto nivel de informalidad y bajo nivel de educación financiera**.

## Riesgos del sector

El sector agrícola dominicano enfrentan riesgos de caractér multidimensional, que afecta negativamente la producción y a su vez, impactan significativamente su capacidad de competir en mercados internacionales:

-   **Los riesgos climáticos**. Huracanes, sequías e inundaciones.

-   **Riesgos de mercados**. Volatilidad en los precios de los rubros agrícolas y la desfavorables posición que poseen los productores agrícolas con los intermediarios en la cadena de valor.

-   **Exposición a riesgos biólogicos**

-   **Limitado acceso a instrumentos financieros** como seguros agrícolas, contratos futuros y mecanismos de cobertura.

## Próposito y objetivo del trabajo

-   **Próposito**

    Desarrollar una metodología de optimización agrícola ajustada por riesgo para maximizar los beneficios económicos de los agricultores, gestionando riesgos y mejorando la productividad sin requerir significativas inversiones adicionales o cambios institucionales.

-   **Objetivo**

Desarrollar y validar una metodología de optimización de portafolio que permita a los agricultores dominicanos maximizar rendimientos ajustados por riesgo mediante una selección óptima de cultivos, considerando restricciones locales y contribuyendo a la sostenibilidad económica del sector agrícola.

## Matríz técnica para el cálculo de la rentabilidad por rubro Agrícola

Para el cálculo de los rendimientos, se emplea la siguiente formula:

$$
\frac{\text{Productividad} \cdot \text{Precio} - \text{costo}}{\text{costo}} \cdot (\text{ciclo})
$$

-   Productividad promedio anual (kg/ha).

-   Precio recibido por el productor (RD\$/kg).

-   Costos totales de producción.

-   Ciclo de cosecha del cultivo.

El numerador refleja los beneficios netos, considerando la diferencia entre los ingresos (productividad multiplicada por precio) y los costos de producción. El denominador, que incluye únicamente los costos totales, permite estandarizar los rendimientos relativos, haciéndolos comparables entre cultivos.

-   **Ventajas**

    -   Facilita la evaluación de rentabilidad sin depender del tamaño de la finca ni del capital inicial, adaptándose a diversas restricciones del mercado agrícola.

    -   La normalización por costos hace que la comparación sea equitativa entre cultivos con diferentes ciclos y frecuencias de cosecha, resaltando la eficiencia económica de cada rubro.
