```{r}
#| include: false
library(tidyverse)
library(dplyr)
library(lmtest)
library(vars)
library(stats)
library(stargazer)
library(ggplot2)
library(AER)
library(readxl)
library(tseries)
library(mFilter)
library(x12)
library(svars)
library(urca)
library(highcharter)
library(psych)
library(PerformanceAnalytics)
library(kableExtra)
library(mFilter)
library(reshape2)
library(stargazer)
```

```{r}
#| include: false
library(readxl)
dataset <- read_excel("dataset.xlsx", sheet = "data_anual")
view(dataset)
```

**Tabla.** Estadísticas descriptivas de precios por rubro

```{r}
#| echo: false

data_clean <- dataset %>%
  dplyr::select(Año, Rubro, Precio_kg) 

stats <- data_clean %>%
  group_by(Rubro) %>%
  summarise(
    Mean = mean(Precio_kg, na.rm = TRUE),
    Median = median(Precio_kg, na.rm = TRUE),
    SD = sd(Precio_kg, na.rm = TRUE),
    Min = min(Precio_kg, na.rm = TRUE),
    Max = max(Precio_kg, na.rm = TRUE),
    Coef_Variation = sd(Precio_kg, na.rm = TRUE) / mean(Precio_kg, na.rm = TRUE)
  )

stats %>%
  kable(
    format = "pipe",
    col.names = c("Rubro", "Media", "Mediana", "Desviación Estándar", "Mínimo", "Máximo", "Coef. de Variación")
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    full_width = F
  )

```

**Gráfica \#**. Evolución de los precios de los rubros agrícolas

```{r}
#| echo: false
ggplot(data_clean, aes(x = Año, y = Precio_kg, color = Rubro, group = Rubro)) +
  geom_line() +
  labs(title = "Evolución de los precios por rubro", x = "Año", y = "Precio (RD$/kg)") +
  theme_minimal() +
  theme(legend.position = "bottom")
```

**Tabla #.** Matriz de correlación de precios por rubro

```{r}
#| echo: false
pivoted_data <- as_tibble(data_clean %>%
  pivot_wider(names_from = Rubro, values_from = Precio_kg))


if ("Año" %in% colnames(pivoted_data)) {
  pivoted_data <- pivoted_data %>% dplyr::select(-Año)
}

#La matriz de correlación
cor_matrix <- cor(pivoted_data, use = "complete.obs")

# 
cor_matrix %>%
  as.data.frame() %>%
  rownames_to_column("Rubros") %>%
  kable(format = "html", caption = "Matriz de correlación de precios por rubro") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)
```